on:
  push:
  pull_request:

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        java-version: [8, 11, 17]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: coursier/cache-action@v6

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - run: ./millw --no-server "__.publishM2Local" test-repo

  publish-sonatype:
    # TODO: also publish release-branches
    if: github.repository == 'com-lihaoyi/millmoduledefs' && startsWith( github.ref, 'refs/tags/')
    needs: [test]

    runs-on: ubuntu-latest

    env:
      LANG: "en_US.UTF-8"
      LC_MESSAGES: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: coursier/cache-action@v6

      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin

      - name: Setup GPG secrets for publish
        run: |
          gpg --version
          cat <(echo "${{ secrets.SONATYPE_PGP_SECRET }}") | base64 --decode | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish to Maven Central
        run: ./millw --no-server mill.scalalib.PublishModule/publishAll --sonatypeCreds "${{ secrets.SONATYPE_DEPLOY_USER }}:${{ secrets.SONATYPE_DEPLOY_PASSWORD }}" --gpgArgs "--passphrase=${{ secrets.SONATYPE_PGP_PASSWORD}},--batch,--yes,-a,-b,--pinentry-mode,loopback" --publishArtifacts __.publishArtifacts --readTimeout 600000 --awaitTimeout 600000 --release true --signed true
